{{- if .Values.persistence.pdName -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pdName }}
  namespace: {{ template "nexus.namespace" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "nexus.fullname" . }}-data
{{- if .Values.persistence.csi }}
  volumeMode: Filesystem
  csi:
{{ toYaml .Values.persistence.csi | indent 4 }}
{{- else }}
  gcePersistentDisk:
    pdName: {{ .Values.persistence.pdName }}
    fsType: {{ .Values.persistence.fsType }}
{{- end }}
{{- end }}